# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thot_wrappers", use_symbols = TRUE, package_name = "thot")

#' @docType package
#' @usage NULL
#' @useDynLib thot, .registration = TRUE
NULL

#' Gets the Project path given a path.
#' Returns `NULL` if the path is not in a project.
#'
#' @param path Path to get the Project root of.
project_resource_root_path <- function(path) .Call(wrap__project_resource_root_path, path)

#' Creates a new Asset.
#'
#' @param path Path of the Asset's file.
new_asset <- function(path) .Call(wrap__new_asset, path)


# nolint end
