[package]
name = "thot-local"
version = "0.10.0-intermediate"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Local functionality for Thot data management and analysis software."
license = "MIT OR Apache-2.0"

homepage = "https://thot-data.com"
repository = "https://github.com/thot-data/local"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "science", "data-structures" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aquamarine = "0.1"  # @todo: Only needed for documentation.
cluFlock = { version = "1.2.7", optional = true }
derivative = "2.2"
directories = { version = "4.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
uuid = { version = "1.2.1", features = ["serde", "v4"] }
validator = "0.14"

has_id = { path  = "../has_id", features = ["derive", "serde"] }
settings_manager = { path = "../settings_manager", optional = true }
thot-core = { path = "../core", features = ["serde"] }
tracing = "0.1.37"

[dev-dependencies]
rand = "0.8"
fake = "2.4"
lazy_static = "1.4.0"

settings_manager_change_path = { path = "../settings_manager/settings_manager_change_path" }
dev_utils = { path = "../dev_utils" }

[features]
default = ["fs"]
fs = ["dep:cluFlock", "dep:directories", "dep:settings_manager"]
