[package]
name = "syre-desktop-workspace-db"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
icondata.workspace = true
leptos_icons.workspace = true
leptos-use.workspace = true
leptos.workspace = true
reactive_stores.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
syre-core.workspace = true
syre-desktop-lib = { path = "../lib" }
syre-desktop-resource-db = { path = "../resource_db", default-features = false }
syre-desktop-ui-lib = { path = "../ui_lib" }
syre-project-watcher.workspace = true
syre-desktop-editors = { path = "../editors" }
tauri-sys = { workspace = true, features = ["core"] }
tracing.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "CssStyleDeclaration",
    "Document",
    "DomRect",
    "Element",
    "Event",
    "HtmlElement",
    "Window",
] }
