[package]
name = "syre-desktop-resource-db"
version = "0.0.0"
edition = "2024"

authors = ["Brian Carlsen <carlsen.bri@gmail.com>"]
description = "Resource database for Syre desktop."
license = "MIT OR Apache-2.0"

homepage = "https://syre.ai"
repository = "https://github.com/syre-data/syre"
keywords = ["syre", "syre-data", "data", "data-analysis", "data-management"]
categories = ["science", "data-structures"]

[dependencies]
chrono.workspace = true
crossbeam = { workspace = true, features = ["crossbeam-channel"] }
derive_more.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
syre-core.workspace = true
syre-local = { workspace = true, optional = true }
syre-project-daemon = { workspace = true, optional = true }
tokio = { version = "1.36", features = ["sync", "rt"], optional = true }
tracing = { workspace = true, optional = true }
tracing-flame = { workspace = true, optional = true }
uuid.workspace = true
zmq = { workspace = true, optional = true }

[dependencies.surrealdb]
version = "3.0"
package = "surrealdb-nightly"
optional = true

[dependencies.tracing-subscriber]
version = "0.3"
optional = true
features = [
    "time",
    "json",
    "env-filter",
]

[features]
default = ["server", "client"]
server = [
    "dep:zmq",
    "surrealdb/kv-mem",
    "syre-project-daemon/client",
    "syre-local",
    "tokio/macros",
    "tokio/rt-multi-thread",
]
client = ["dep:surrealdb", "dep:tokio"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
perf = ["tracing", "dep:tracing-flame"]

# NB: Release profile configured in workspace root.