[package]
name = "syre-desktop-resource-db"
version = "0.0.1"
edition = "2024"

authors = ["Brian Carlsen <carlsen.bri@gmail.com>"]
description = "Resource database for Syre desktop."
license = "MIT OR Apache-2.0"

homepage = "https://syre.ai"
repository = "https://github.com/syre-data/syre"
keywords = ["syre", "syre-data", "data", "data-analysis", "data-management"]
categories = ["science", "data-structures"]

[dependencies]
chrono.workspace = true
crossbeam = { workspace = true, features = ["crossbeam-channel"] }
derive_more.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
surrealdb = { version = "2.1", package = "surrealdb-nightly", optional = true }
syre-core.workspace = true
syre-local = { workspace = true, optional = true }
syre-project-watcher = { workspace = true, optional = true }
tokio = { version = "1.36", features = ["sync"], optional = true }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [
    "time",
    "json",
    "env-filter",
] }
uuid.workspace = true
zmq = { workspace = true, optional = true }

[features]
default = ["server", "client"]
server = [
    "surrealdb/kv-mem",
    "syre-project-watcher/client",
    "syre-local",
    "tokio/macros",
    "tokio/rt-multi-thread",
    "zmq",
]
client = ["surrealdb", "tokio"]

# NB: Release profile configured in workspace root.
