[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "desktop",
    "desktop/src-lib",
    "desktop/src-tauri",
    "dev_utils",
    "file_path_from_id",
    "has_id",
    "has_id/has_id_derive",
    "lang/rust",
    "local",
    "local/database",
    "local/database/cli",
    "local/runner",
    "ui",
]

[workspace.dependencies]
aquamarine = "0.3"
calamine = "0.23"
clap = "4.4"
csv = "1.3"
directories = "5.0"
indexmap = "2.1"
js-sys = "0.3"
rayon = "1.8"
regex = "1.10"
serde = "1.0"
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
serde_with = "3.4"
tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys" }
thiserror = "1.0"
tracing = "0.1"
trash = "3.3"
uuid = { version = "1.3", features = ["v4"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = "0.21"
yew-router = "0.18"
yew_icons = "0.8"
zmq = "0.10.0"

# dev dependencies
fake = "2.4"
rand = "0.8"
tempfile = "3"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false