[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "desktop",
    "desktop/src-lib",
    "desktop/src-tauri",
    "dev_utils",
    "has_id",
    "has_id/has_id_derive",
    "lang/rust",
    "local",
    "local/database",
    "local/database/cli",
    "local/runner",
    "ui",
]

[workspace.dependencies]
clap = "4.4"
directories = "5.0"
indexmap = "2.1"
js-sys = "0.3"
serde_json = "1.0"
tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys" }
tracing = "0.1"
uuid = { version = "1.3", features = ["v4"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = "0.21"
yew-router = "0.18"
yew_icons = "0.8"
zmq = "0.10.0"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
