[package]
name = "thot-local-database"
version = "0.0.1"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Local database for Thot resources."
license = "MIT OR Apache-2.0"

homepage = "https://thot.so"
repository = "https://github.com/thot-data/thot"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "science", "data-structures" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["time", "json"] }
trash = { version = "3.0.1", optional = true }
zmq = { version = "0.10", optional = true }

has_id = { path = "../../has_id", optional = true }
settings_manager = { path = "../../settings_manager", optional = true }
thot-core = { path = "../../core" }
thot-local = { path = "..", default-features = false }


[dev-dependencies]
rand = "0.8"
fake = "2.4"
lazy_static = "1.4"

dev_utils = { path = "../../dev_utils" }

[features]
server = ["dep:zmq", "dep:settings_manager", "thot-local/fs", "dep:has_id", "dep:trash"]
client = ["dep:zmq"]
