[package]
name = "thot-local-database"
version = "0.0.1"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Local database for Thot resources."
license = "MIT OR Apache-2.0"

homepage = "https://thot-data.com"
repository = "https://github.com/thot-data/local"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "science", "data-structures" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
zmq = { version = "0.10.0", optional = true }

settings_manager = { path = "../../settings_manager", optional = true }
thot-core = { path = "../../core" }
thot-local = { path = "..", default-features = false }

[dev-dependencies]
rand = "0.8"
fake = "2.4"
lazy_static = "1.4.0"

dev_utils = { path = "../../dev_utils" }

[features]
server = ["dep:zmq", "dep:settings_manager", "thot-local/fs"]
client = ["dep:zmq"]
