[package]
name = "thot-local-database"
version = "0.0.2"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Local database for Thot resources."
license = "MIT OR Apache-2.0"

homepage = "https://thot.so"
repository = "https://github.com/thot-data/thot"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "science", "data-structures" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
indexmap = { workspace = true, features = ["serde"] }
notify = { version = "6.1", default-features = false, features = ["macos_kqueue"], optional = true}
notify-debouncer-full = { version = "0.3", default-features = false, optional = true}
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["time", "json"] }
trash = { version = "3.0", optional = true }
zmq = { workspace = true, optional = true }

has_id = { path = "../../has_id", optional = true }
thot-core = { path = "../../core" }
thot-local = { path = "..", default-features = false }

[dev-dependencies]
rand = "0.8"
fake = "2.4"
lazy_static = "1.4"

dev_utils = { path = "../../dev_utils", features = ["thot_core"] }

[features]
default = ["error"]
server = ["dep:zmq", "thot-local/fs", "dep:has_id", "dep:trash", "dep:notify", "dep:notify-debouncer-full"]
client = ["dep:zmq"]
error = []
