# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thot_wrappers", use_symbols = TRUE, package_name = "thot")

#' @docType package
#' @usage NULL
#' @useDynLib thot, .registration = TRUE
NULL

#' Return whether Thot is running in development mode.
#' @export
dev_mode <- function() .Call(wrap__dev_mode)

#' Return whether Thot is running in development mode.
#' @export
create_database <- function() .Call(wrap__create_database)

#' Return whether Thot is running in development mode.
#' @export
find_containers <- function() .Call(wrap__find_containers)

#' Return whether Thot is running in development mode.
#' @export
find_container <- function() .Call(wrap__find_container)

#' Return whether Thot is running in development mode.
#' @export
find_assets <- function() .Call(wrap__find_assets)

#' Return whether Thot is running in development mode.
#' @export
find_asset <- function() .Call(wrap__find_asset)


# nolint end
