# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thot_wrappers", use_symbols = TRUE, package_name = "thot")

#' @docType package
#' @usage NULL
#' @useDynLib thot, .registration = TRUE
NULL

#' Return whether Thot is running in development mode.
#' @export
dev_mode <- function() .Call(wrap__dev_mode)

#' Return whether Thot is running in development mode.
#' @export
database <- function(dev_root = NULL) .Call(wrap__database, dev_root)

Database <- new.env(parent = emptyenv())

Database$temp <- function() .Call(wrap__Database__temp, self)

#' @export
`$.Database` <- function (self, name) { func <- Database[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Database` <- `$.Database`

Container <- new.env(parent = emptyenv())

Container$name <- function() .Call(wrap__Container__name, self)

#' @export
`$.Container` <- function (self, name) { func <- Container[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Container` <- `$.Container`


# nolint end
