[package]
name = "syre-desktop-ui-components"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
leptos.workspace = true
leptos_icons.workspace = true
leptos_router = { workspace = true, features = ["nightly"] }
leptos-use = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
syre-core.workspace = true
syre-desktop-lib = { path = "../lib" }
syre-desktop-ui-lib = { path = "../ui_lib" }
syre-local.workspace = true
tauri-sys = { workspace = true, features = ["core"] }
tracing = { workspace = true, optional = true }
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
	"DomRect",
	"Element",
	"Event",
	"EventTarget",
	"FocusEvent",
	"HtmlDialogElement",
	"HtmlElement",
]

[features]
tracing = ["dep:tracing"]