[package]
name = "thot-desktop-lib"
version = "0.10.0"
description = "Shared types and functionality for the front- and back-end of Thot desktop."
authors = ["Brian Carlsen <carlsen.bri@gmail.com>"]

homepage = "https://thot.so"
repository = "https://github.com/thot-data/thot"
keywords = ["thot", "thot-data"]
categories = []
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = { workspace = true }
csv = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }

thot-core = { path = "../../core", features = ["serde"] }
thot-local = { path = "../../local", default-features = false }
