[package]
name = "thot-desktop-tauri"
version = "0.10.0"
description = "Thot desktop application."
authors = ["Brian Carlsen <carlsen.bri@gmail.com>"]

homepage = "https://thot.so"
repository = "https://github.com/thot-data/thot"
keywords = ["thot", "thot-data", "data", "data-analysis", "data-management"]
categories = ["gui", "science"]
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
cluFlock = "1.2"
directories = "4.0"
open = "3.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.44"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["time", "json"] }
uuid = { version = "1.2", features = ["serde", "v4"] }
tauri = { version = "1.5", features = ["dialog-open", "process-command-api", "shell-sidecar", "system-tray", "updater"] }
zmq = "0.10.0"

thot-core = { path = "../../core", features = ["serde"] }
thot-desktop-lib = { path = "../src-lib" }
thot-local = { path = "../../local" }
thot-local-database = { path = "../../local/database", features = ["server", "client"] }
thot-local-runner = { path = "../../local/runner" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
