[package]
name = "syre-desktop"
version = "0.11.10"
description = "Syre desktop application."
authors = ["Brian Carlsen <carlsen.bri@gmail.com>"]
edition = "2024"

homepage = "https://syre.ai"
repository = "https://github.com/syre-data/syre"
keywords = ["syre", "syre-data", "data", "data-analysis", "data-management"]
categories = ["gui", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2", features = [] }

[dependencies]
derive_more.workspace = true
directories.workspace = true
ignore.workspace = true
open = "5.3.0"
rayon.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
syre-core = { workspace = true, features = ["serde"] }
syre-local = { workspace = true, features = ["fs"] }
syre-project-daemon = { workspace = true, features = ["client"] }
syre-local-runner = { workspace = true }
syre-desktop-lib = { path = "../crates/lib", features = ["server"] }
syre-desktop-resource-db = { path = "../crates/resource_db" }
tauri = { version = "2.5", features = [] }
tauri-plugin-dialog = "2.2"
tauri-plugin-shell = "2.2"
tempfile.workspace = true
tokio = { version = "1.42", features = ["full"] }
tokio-stream = { version = "0.1", features = ["full"] }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = [
    "json",
    "time",
	"env-filter",
], optional = true }
tracing-appender = { workspace = true, optional = true }
tracing-timing = { version = "0.7", features = ["layer"], optional = true}
trash.workspace = true
uuid.workspace = true
walkdir.workspace = true
zmq.workspace = true
tauri-plugin-store = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"

[features]
no-auto-update = []
tracing = [
    "dep:tracing",
    "dep:tracing-subscriber",
    "dep:tracing-appender",
    "dep:tracing-timing",
]
