# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_thot_wrappers", use_symbols = TRUE, package_name = "thot")

#' @docType package
#' @usage NULL
#' @useDynLib thot, .registration = TRUE
NULL

#' Return whether Thot is running in development mode.
#' @export
dev_mode <- function() .Call(wrap__dev_mode)

#' Return whether Thot is running in development mode.
#' @export
database <- function(dev_root = NULL) .Call(wrap__database, dev_root)

#' Find a single Thot Container.
#' If multiple are found, a single one is returned.
#' @export
find_container <- function(db, `_id` = NULL, name = NULL, type = NULL, tags = NULL, metadata = NULL) .Call(wrap__find_container, db, `_id`, name, type, tags, metadata)

#' Find Thot Containers matching the filter criteria.
#' @export
find_containers <- function(db, `_id` = NULL, name = NULL, type = NULL, tags = NULL, metadata = NULL) .Call(wrap__find_containers, db, `_id`, name, type, tags, metadata)

#' Find a single Thot Asset.
#' If multiple are found, a single one is returned.
#' @export
find_asset <- function(db, `_id` = NULL, name = NULL, type = NULL, tags = NULL, metadata = NULL) .Call(wrap__find_asset, db, `_id`, name, type, tags, metadata)

#' Find Thot Assets matching the filter criteria.
#' @export
find_assets <- function(db, `_id` = NULL, name = NULL, type = NULL, tags = NULL, metadata = NULL) .Call(wrap__find_assets, db, `_id`, name, type, tags, metadata)

#' Create a new Thot Asset with the given properties.
#' The related data should be saved at the returned path.
#' @export
add_asset <- function(db, file, name = NULL, type = NULL, description = NULL, tags = NULL, metadata = NULL) .Call(wrap__add_asset, db, file, name, type, description, tags, metadata)

Database <- new.env(parent = emptyenv())

Database$root <- function() .Call(wrap__Database__root, self)

#' @export
`$.Database` <- function (self, name) { func <- Database[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Database` <- `$.Database`

Container <- new.env(parent = emptyenv())

Container$name <- function() .Call(wrap__Container__name, self)

Container$kind <- function() .Call(wrap__Container__kind, self)

Container$tags <- function() .Call(wrap__Container__tags, self)

#' @export
`$.Container` <- function (self, name) { func <- Container[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Container` <- `$.Container`

Asset <- new.env(parent = emptyenv())

Asset$name <- function() .Call(wrap__Asset__name, self)

Asset$kind <- function() .Call(wrap__Asset__kind, self)

Asset$tags <- function() .Call(wrap__Asset__tags, self)

#' @export
`$.Asset` <- function (self, name) { func <- Asset[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Asset` <- `$.Asset`


# nolint end
