[package]
name = "thot-ui"
version = "0.10.0"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Thot UI elements."

homepage = "https://thot-data.com"
repository = "https://github.com/thot-data/ui"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "gui", "science" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
js-sys = "0.3.60"
tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys", features = ["dialog", "event"] }
serde_json = "1.0"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.33"
yew = "0.20"
yew-router = "0.17"

thot-core = { path = "../core", features = ["js", "yew"] }

[dependencies.web-sys]
version = "0.3.59"
features=[
    "DataTransfer",
	"DomStringMap",
    "DragEvent",
	"Event",
	"EventTarget",
	"HtmlButtonElement",
    "HtmlDivElement",
	"HtmlSelectElement",
	"HtmlTextAreaElement",
	"MediaQueryList",
	"MediaQueryListEvent",
	"Window",
]

[dev-dependencies]
fake = "2.4"
wasm-bindgen-test = "0.3"
