[package]
name = "thot-desktop"
version = "0.10.0"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Thot desktop application."

homepage = "https://thot-data.com"
repository = "https://github.com/thot-data/desktop"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "gui", "science" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
aquamarine = "0.1"  # @todo: Only needed for documentation.
futures = "0.3"
gloo-storage = "0.2.2"
indexmap = "1.9.2"
js-sys = "0.3.59"
serde = { version = "1.0.140", features = ["derive"] }
serde-wasm-bindgen = "0.4.3"
# tauri-sys = { path = "/home/brian/Downloads/tauri-sys-fs/tauri-sys", features = ["dialog", "event", "fs", "path"] }
# tauri-sys = { git = "https://github.com/bicarlsen/tauri-sys", branch = "fs", features = ["dialog", "event", "fs", "path"] }
tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys", features = ["dialog", "event", "path"] }
uuid = { version = "1.2.1", features = ["serde", "v4"] }
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"

thot-core = { path = "../core", features = ["yew", "serde"] }
thot-local = { path = "../local", default-features = false }
thot-ui = { path = "../ui" }
thot-desktop-lib = { path = "src-lib" }
thot-local-database = { path = "../local/database" }

serde_json = "1.0.91" # @todo: Remove. Only required for https://github.com/tauri-apps/tauri/issues/6078

[dependencies.web-sys]
version = "0.3.59"
features = [
    "DomStringMap",
    "DragEvent",
    "Event",
    "FocusEvent",
    "HtmlInputElement",
    "InputEvent",
    "SubmitEvent",
]
