[package]
name = "thot-desktop"
version = "0.10.0"
edition = "2021"

authors = [ "Brian Carlsen <carlsen.bri@gmail.com>" ]
description = "Thot desktop application."

homepage = "https://thot.so"
repository = "https://github.com/thot-data/thot"
keywords = [ "thot", "thot-data", "data", "data-analysis", "data-management" ]
categories = [ "gui", "science" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
aquamarine = "0.1" # TODO: Only needed for documentation.
futures = "0.3"
gloo-storage = "0.2"
gloo-timers = "0.2.6"
indexmap = "1.9"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys", features = ["dialog", "event", "path"] }
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["time"] }
tracing-web = "0.1.2"
uuid = { version = "1.2", features = ["js", "serde", "v4"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"

thot-core = { path = "../core", features = ["yew", "serde"] }
thot-local = { path = "../local", default-features = false }
thot-ui = { path = "../ui" }
thot-desktop-lib = { path = "src-lib" }
thot-local-database = { path = "../local/database" }

serde_json = "1.0" # TODO: Only required for https://github.com/tauri-apps/tauri/issues/6078.

[dependencies.web-sys]
version = "0.3"
features = [
    "DomStringMap",
    "DragEvent",
    "Event",
    "FocusEvent",
    "HtmlElement",
    "HtmlInputElement",
    "InputEvent",
    "SubmitEvent",
    "SvgCircleElement",
    "SvggElement",
    "SvgForeignObjectElement",
    "SvgPolylineElement",
    "SvgsvgElement",
    "SvgUseElement",
]

[dependencies.yew_icons]
version = "0.7"
features = [
    "FontAwesomeRegularEye",
    "FontAwesomeRegularEyeSlash",
]
