[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri-0", "./src-lib"]

[serve]
address = "0.0.0.0"
port = 1420
open = false
ws_protocol = "ws"

# *nix
# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss -i styles/main.css -o styles/output.css"]

# Windows
[[hooks]]
stage = "pre_build"
command = "cmd"
command_arguments = ["/c npx tailwindcss -i styles/main.css -o styles/output.css"]
